In [1]:
import numpy as np

In [2]:
x = np.array([1,5,2])
y = np.array([7,4,1])

In [3]:
x + y

array([8, 9, 3])

In [4]:
x * y

array([ 7, 20,  2])

In [5]:
x - y

array([-6,  1,  1])

In [6]:
x / y

array([0.14285714, 1.25      , 2.        ])

In [7]:
x % y

array([1, 1, 0])

In [29]:
x = np.array([3,2])
y = np.array([5,1])

In [31]:
z = x + y
z

array([8, 3])

In [32]:
z = x - y
z

array([-2,  1])

In [33]:
x = np.array([1,2,3])
y = np.array([-7,8,9])

In [37]:
dot = np.dot(x,y)
dot

In [38]:
x_modulus = np.sqrt((x*x).sum())
y_modulus = np.sqrt((y*y).sum())

cos_angle = dot / x_modulus / y_modulus
angle = np.arccos(cos_angle)

In [39]:
angle

0.808233789010825

In [41]:
angle * 360 / 2 / np.pi

46.308384970187326

In [49]:
x = np.array( ((2,3), (3, 5)) )
y = np.array( ((1,2), (5, -1)))

In [44]:
x

array([[2, 3],
       [3, 5]])

In [45]:
y

array([[ 1,  2],
       [ 5, -1]])

In [43]:
x * y

array([[ 2,  6],
       [15, -5]])

In [46]:
x = np.matrix( ((2,3), (3, 5)) )
y = np.matrix( ((1,2), (5, -1)))

In [47]:
x * y

matrix([[17,  1],
        [28,  1]])

In [51]:
x = np.array( ((2,3), (3, 5)) )
y = np.array( ((1,2), (5, -1)))

In [52]:
np.dot(x,y)

array([[17,  1],
       [28,  1]])

In [53]:
np.mat(x) * np.mat(y)

matrix([[17,  1],
        [28,  1]])

In [56]:
a = np.arange(9).reshape(3, 3)

In [57]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
print (a[[0, 2], :])

[[0 1 2]
 [6 7 8]]


In [59]:
A=np.mat(a)

In [83]:
A

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [82]:
A = np.mat([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [63]:
A.T

matrix([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [65]:
A.A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
A.A1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
A+np.eye(3)

matrix([[1., 1., 2.],
        [3., 5., 5.],
        [6., 7., 9.]])

In [69]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
A*2

matrix([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [72]:
A**2

matrix([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [77]:
b = np.mat('1; 2; 3')
b

matrix([[1],
        [2],
        [3]])

In [78]:
A*b

matrix([[ 8],
        [26],
        [44]])

In [79]:
b.T * A

matrix([[24, 30, 36]])

In [80]:
(b.T * A).A1

array([24, 30, 36])

Cгенерировать array (5,3):  

[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
 
 Показать 2 и 4 строки
 


Cгенерировать матрицу A
[[3, 1, 4],
 [1, 5, 9],
 [2, 6, 5]]
и колоночный вектор b
[[1],
 [2],
 [3]]
вычислить x = A.I * b